parameters:
    app.date_range.form.type.class:                 ReportBundle\Form\Type\DateRangeType
    app.abstract_report.form.type.class:            ReportBundle\Form\Type\AbstractReportType
    app.report_appointments.form.type.class:        ReportBundle\Form\Type\AppointmentsType
    app.report_patients.form.type.class:            ReportBundle\Form\Type\PatientsType
    app.report_recalls.form.type.class:             ReportBundle\Form\Type\RecallsType
    app.report_patient_retention.form.type.class:   ReportBundle\Form\Type\PatientRetentionType
    app.report_invoices.form.type.class:            ReportBundle\Form\Type\InvoicesType
    app.report_revenue.form.type.class:             ReportBundle\Form\Type\RevenueType
    app.report_products.form.type.class:            ReportBundle\Form\Type\ProductsType
    app.report_products_purchased.form.type.class:  ReportBundle\Form\Type\ProductsPurchasedType

services:

    app.date_range.form.type:
        class: "%app.date_range.form.type.class%"
        arguments:
            - "@app.formatter"
        tags:
            - { name: form.type, alias: app_date_range }

    app.date_range.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_date_range"
            - "app_date_range"

#===============================================================

    app.report_appointments.form.type:
        class: "%app.report_appointments.form.type.class%"
        tags:
            - { name: form.type, alias: app_report_appointments }

    app.report_appointments.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_appointments"
            - "app_report_appointments"

#===============================================================

    app.report_patients.form.type:
        class: "%app.report_patients.form.type.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: app_report_patients }

    app.report_patients.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_patients"
            - "app_report_patients"

#===============================================================

    app.report_recalls.form.type:
        class: "%app.report_recalls.form.type.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: app_report_recalls }

    app.report_recalls.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_recalls"
            - "app_report_recalls"

#===============================================================

    app.report_patient_retention.form.type:
        class: "%app.report_patient_retention.form.type.class%"
        arguments:
            - "@app.event_utils"
        tags:
            - { name: form.type, alias: app_report_patient_retention }

    app.report_patient_retention.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_patient_retention"
            - "app_report_patient_retention"

#===============================================================

    app.report_revenue.form.type:
        class: "%app.report_revenue.form.type.class%"
        tags:
            - { name: form.type, alias: app_report_revenue }

    app.report_revenue.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_revenue"
            - "app_report_revenue"

#===============================================================

    app.report_products.form.type:
        class: "%app.report_products.form.type.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: app_report_products }

    app.report_products.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_products"
            - "app_report_products"

#===============================================================

    app.report_products_purchased.form.type:
        class: "%app.report_products_purchased.form.type.class%"
        arguments:
            - "@fos_user.entity_manager"
        tags:
            - { name: form.type, alias: app_report_products_purchased }

    app.report_products_purchased.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_products_purchased"
            - "app_report_products_purchased"

#===============================================================

    app.report_invoices.form.type:
        class: "%app.report_invoices.form.type.class%"
        tags:
            - { name: form.type, alias: app_report_invoices }

    app.report_invoices.form:
        class:           Symfony\Component\Form\Form
        factory: ["@form.factory", createNamed]
        arguments:
            - "app_report_invoices"
            - "app_report_invoices"
