parameters:
    app.report_provider.abstract.class:           ReportBundle\Provider\AbstractReportProvider
    app.xls_formatter.abstract.class:             ReportBundle\Formatter\AbstractXlsFormatter

    app.report_provider.appointments.class:       ReportBundle\Provider\AppointmentsProvider
    app.xls_formatter.appointments.class:         ReportBundle\Formatter\AppointmentsXlsFormatter

    app.report_provider.patients.class:           ReportBundle\Provider\PatientsProvider
    app.xls_formatter.patients.class:             ReportBundle\Formatter\PatientsXlsFormatter

    app.report_provider.invoices.class:           ReportBundle\Provider\InvoicesProvider
    app.xls_formatter.invoices.class:             ReportBundle\Formatter\InvoicesXlsFormatter

    app.report_provider.revenue.class:            ReportBundle\Provider\RevenueProvider
    app.xls_formatter.revenue.class:              ReportBundle\Formatter\RevenueXlsFormatter

    app.report_provider.products.class:           ReportBundle\Provider\ProductsProvider
    app.xls_formatter.products.class:             ReportBundle\Formatter\ProductsXlsFormatter

    app.report_provider.products_purchased.class: ReportBundle\Provider\ProductsPurchasedProvider
    app.xls_formatter.products_purchased.class:   ReportBundle\Formatter\ProductsPurchasedXlsFormatter

services:

    app.report_provider.abstract:
        class: "%app.report_provider.abstract.class%"
        abstract: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router.default"
            - "@app.formatter"
            - "@translator.default"
            - "@app.hasher"

    app.xls_formatter.abstract:
        class: "%app.xls_formatter.abstract.class%"
        abstract: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator.default"
            - "@app.formatter_extension"
            - "@app.price_extension"

#===============================================================

    app.report_provider.revenue:
        parent: "app.report_provider.abstract"
        class: "%app.report_provider.revenue.class%"

    app.xls_formatter.revenue:
        parent: "app.xls_formatter.abstract"
        class: "%app.xls_formatter.revenue.class%"

#===============================================================

    app.report_provider.products:
        parent: "app.report_provider.abstract"
        class: "%app.report_provider.products.class%"

    app.xls_formatter.products:
        parent: "app.xls_formatter.abstract"
        class: "%app.xls_formatter.products.class%"

#===============================================================

    app.report_provider.products_purchased:
        parent: "app.report_provider.abstract"
        class: "%app.report_provider.products_purchased.class%"

    app.xls_formatter.products_purchased:
        parent: "app.xls_formatter.abstract"
        class: "%app.xls_formatter.products_purchased.class%"

#===============================================================

    app.report_provider.appointments:
        parent: "app.report_provider.abstract"
        class: "%app.report_provider.appointments.class%"
        calls:
            - ['setEventUtils',["@app.event_utils"]]

    app.xls_formatter.appointments:
        parent: "app.xls_formatter.abstract"
        class: "%app.xls_formatter.appointments.class%"

#===============================================================

    app.report_provider.patients:
        parent: "app.report_provider.abstract"
        class: "%app.report_provider.patients.class%"
        calls:
            - ['setEventUtils',["@app.event_utils"]]

    app.xls_formatter.patients:
        parent: "app.xls_formatter.abstract"
        class: "%app.xls_formatter.patients.class%"

#===============================================================

    app.report_provider.invoices:
        parent: "app.report_provider.abstract"
        class: "%app.report_provider.invoices.class%"

    app.xls_formatter.invoices:
        parent: "app.xls_formatter.abstract"
        class: "%app.xls_formatter.invoices.class%"

#===============================================================

