parameters:
    app.profile.form.type.class:                  UserBundle\Form\Type\ProfileType
    app.registration.form.type.class:             UserBundle\Form\Type\RegistrationType
    app.change_password.form.type.class:          UserBundle\Form\Type\ChangePasswordFormType
    app.registration_confirmed.form.type.class:   UserBundle\Form\Type\RegistrationConfirmedType

services:

    app.profile.form:
        class: '%app.profile.form.type.class%'
        tags:
            - { name: form.type, alias: app_user_profile }

    app.registration.form:
        class: '%app.registration.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_user_registration }

    app.change_password.form:
        class: '%app.change_password.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_user_change_password }

    app.registration_confirmed.form.type:
        class: '%app.registration_confirmed.form.type.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: app_user_registration_confirmed}

    app.registration_confirmed.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_user_registration_confirmed'
            - '%app.registration_confirmed.form.type.class%'
