parameters:
    app.user_listener.class: UserBundle\EventListener\UserListener

services:
    app.user_listener:
        class: '%app.user_listener.class%'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
