parameters:
    app.profile.form.type.class:                AppBundle\Form\Type\ProfileType
    app.title_selector.form.type.class:         AppBundle\Form\Type\TitleFieldType
    app.country_selector.form.type.class:       AppBundle\Form\Type\CountryFieldType
    app.timezone_selector.form.type.class:      AppBundle\Form\Type\TimezoneFieldType
    app.state_selector.form.type.class:         AppBundle\Form\Type\StateFieldType
    app.patient_selector.form.type.class:       AppBundle\Form\Type\PatientFieldType
    app.subscription_selector.form.type.class:  AppBundle\Form\Type\SubscriptionFieldType
    app.registration.form.type.class:           AppBundle\Form\Type\RegistrationType
    app.patient.form.type.class:                AppBundle\Form\Type\PatientType
    app.related_patient.form.type.class:        AppBundle\Form\Type\RelatedPatientType
    app.phone.form.type.class:                  AppBundle\Form\Type\PhoneType

services:

############################ Entity form types ############################

    app.patient.form.type:
        class: '%app.patient.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_patient}

    app.patient.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'myhs_patient'
            - '%app.patient.form.type.class%'

    app.phone.form.type:
        class: '%app.phone.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_phone}

    app.phone.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'myhs_phone'
            - '%app.phone.form.type.class%'

    app.related_patient.form.type:
        class: '%app.related_patient.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_related_patient}

    app.related_patient.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'myhs_related_patient'
            - '%app.related_patient.form.type.class%'

############################ Field types ############################

    app.country_selector.form.type:
        class: '%app.country_selector.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_country_selector}

    app.title_selector.form.type:
        class: '%app.title_selector.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_title_selector}

    app.timezone_selector.form.type:
        class: '%app.timezone_selector.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_timezone_selector}

    app.subscription_selector.form.type:
        class: '%app.subscription_selector.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_subscription_selector}

    app.state_selector.form.type:
        class: '%app.state_selector.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_state_selector}

    app.patient_selector.form.type:
        class: '%app.patient_selector.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_patient_selector}

############################ FOSUserBundle form tweaks ############################

    app.profile.form:
        class: '%app.profile.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_user_profile }

    app.registration.form:
        class: '%app.registration.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_user_registration }
