parameters:
    app.title_selector.form.type.class:             AppBundle\Form\Type\TitleFieldType
    app.country_selector.form.type.class:           AppBundle\Form\Type\CountryFieldType
    app.timezone_selector.form.type.class:          AppBundle\Form\Type\TimezoneFieldType
    app.state_selector.form.type.class:             AppBundle\Form\Type\StateFieldType
    app.patient_selector.form.type.class:           AppBundle\Form\Type\PatientFieldType
    app.subscription_selector.form.type.class:      AppBundle\Form\Type\SubscriptionFieldType
    app.patient.form.type.class:                    AppBundle\Form\Type\PatientType
    app.patient_notifications.form.type.class:      AppBundle\Form\Type\PatientNotificationsType
    app.patient_alert.form.type.class:              AppBundle\Form\Type\PatientAlertType
    app.related_patient.form.type.class:            AppBundle\Form\Type\RelatedPatientType
    app.phone.form.type.class:                      AppBundle\Form\Type\PhoneType
    app.treatment_note_template.form.type.class:    AppBundle\Form\Type\TreatmentNoteTemplateType
    app.product.form.type.class:                    AppBundle\Form\Type\ProductType
    app.treatment.form.type.class:                  AppBundle\Form\Type\TreatmentType
    app.price_field.form.type.class:                AppBundle\Form\Type\PriceFieldType
    app.invoice.form.type.class:                    AppBundle\Form\Type\InvoiceType
    app.invoice_due_date_selector.form.type.class:  AppBundle\Form\Type\InvoiceDueDateFieldType
    app.product_selector.form.type.class:           AppBundle\Form\Type\ProductFieldType
    app.treatment_selector.form.type.class:         AppBundle\Form\Type\TreatmentFieldType
    app.invoice_product.form.type.class:            AppBundle\Form\Type\InvoiceProductType
    app.invoice_treatment.form.type.class:          AppBundle\Form\Type\InvoiceTreatmentType
    app.attachment.form.type.class:                 AppBundle\Form\Type\AttachmentType
    app.colorpicker.form.type.class:                AppBundle\Form\Type\ColorpickerType
    app.concession.form.type.class:                 AppBundle\Form\Type\ConcessionType
    app.abstract_filter.form.type.class:            AppBundle\Form\Type\Filter\FilterType
    app.patient_filter.form.type.class:             AppBundle\Form\Type\Filter\PatientFilterType
    app.string_filter.form.type.class:              AppBundle\Form\Type\Filter\StringFilterType
    app.concession_price.form.type.class:           AppBundle\Form\Type\ConcessionPriceType
    app.concession_prices.form.type.class:          AppBundle\Form\Type\ConcessionPricesType

services:

############################ Entity form types ############################

    app.patient.form.type:
        class: '%app.patient.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_patient}

    app.patient.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_patient'
            - '%app.patient.form.type.class%'

    app.patient_notifications.form.type:
        class: '%app.patient_notifications.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_patient_notifications}

    app.patient_notifications.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_patient_notifications'
            - '%app.patient_notifications.form.type.class%'

    app.patient_alert.form.type:
        class: '%app.patient_alert.form.type.class%'
        tags:
            - { name: form.type, alias: app_patient_alert}

    app.patient_alert.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_patient_alert'
            - '%app.patient_alert.form.type.class%'

    app.phone.form.type:
        class: '%app.phone.form.type.class%'
        tags:
            - { name: form.type, alias: app_phone}

    app.phone.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_phone'
            - '%app.phone.form.type.class%'

    app.related_patient.form.type:
        class: '%app.related_patient.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_related_patient}

    app.related_patient.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_related_patient'
            - '%app.related_patient.form.type.class%'

    app.treatment_note_template.form.type:
        class: '%app.treatment_note_template.form.type.class%'
        tags:
            - { name: form.type, alias: app_treatment_note_template}

    app.treatment_note_template.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_treatment_note_template'
            - '%app.treatment_note_template.form.type.class%'

    app.product.form.type:
        class: '%app.product.form.type.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: app_product}

    app.product.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_product'
            - '%app.product.form.type.class%'

    app.concession.form.type:
        class: '%app.concession.form.type.class%'
        tags:
            - { name: form.type, alias: app_concession}

    app.concession.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_concession'
            - '%app.concession.form.type.class%'

    app.treatment.form.type:
        class: '%app.treatment.form.type.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: app_treatment}

    app.treatment.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_treatment'
            - '%app.treatment.form.type.class%'

    app.invoice.form.type:
        class: '%app.invoice.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_invoice}

    app.invoice.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_invoice'
            - '%app.invoice.form.type.class%'

    app.invoice_product.form.type:
        class: '%app.invoice_product.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_invoice_product}

    app.invoice_product.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_invoice'
            - '%app.invoice_product.form.type.class%'

    app.concession_price.form.type:
        class: '%app.invoice_product.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_concession_price}

    app.concession_price.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_concession_price'
            - '%app.concession_price.form.type.class%'

    app.invoice_treatment.form.type:
        class: '%app.invoice_treatment.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_invoice_treatment}

    app.invoice_treatment.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_invoice'
            - '%app.invoice_treatment.form.type.class%'

    app.attachment.form.type:
        class: '%app.attachment.form.type.class%'
        tags:
            - { name: form.type, alias: app_attachment}

    app.attachment.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_attachment'
            - '%app.attachment.form.type.class%'

############################ Field types ############################

    app.country_selector.form.type:
        class: '%app.country_selector.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_country_selector}

    app.title_selector.form.type:
        class: '%app.title_selector.form.type.class%'
        tags:
            - { name: form.type, alias: app_title_selector}

    app.colorpicker.form.type:
        class: '%app.colorpicker.form.type.class%'
        tags:
            - { name: form.type, alias: app_colorpicker}

    app.timezone_selector.form.type:
        class: '%app.timezone_selector.form.type.class%'
        tags:
            - { name: form.type, alias: app_timezone_selector}

    app.subscription_selector.form.type:
        class: '%app.subscription_selector.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_subscription_selector}

    app.state_selector.form.type:
        class: '%app.state_selector.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_state_selector}

    app.patient_selector.form.type:
        class: '%app.patient_selector.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_patient_selector}

    app.price_field.form.type:
        class: '%app.price_field.form.type.class%'
        tags:
            - { name: form.type, alias: app_price}

    app.invoice_due_date_selector.form.type:
        class: '%app.invoice_due_date_selector.form.type.class%'
        tags:
            - { name: form.type, alias: app_invoice_due_date_selector}

    app.product_selector.form.type:
        class: '%app.product_selector.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_product_selector}

    app.treatment_selector.form.type:
        class: '%app.treatment_selector.form.type.class%'
        arguments:
            - "@app.hasher"
        tags:
            - { name: form.type, alias: app_treatment_selector}

    app.concession_prices.form.type:
        class: '%app.concession_prices.form.type.class%'
        arguments:
            - '@translator.default'
        tags:
            - { name: form.type, alias: app_concession_prices}

############################ Filter types ############################

    app.abstract_filter.form.type:
        class: '%app.abstract_filter.form.type.class%'
        arguments:
            - '@session'
        tags:
            - { name: form.type, alias: app_filter}

    app.abstract_filter.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_filter'
            - '%app.abstract_filter.form.type.class%'

    app.patient_filter.form.type:
        class: '%app.patient_filter.form.type.class%'
        parent: 'app.abstract_filter.form.type'
        tags:
            - { name: form.type, alias: app_patient_filter}

    app.patient_filter.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_patient_filter'
            - '%app.patient_filter.form.type.class%'

    app.string_filter.form.type:
        class: '%app.string_filter.form.type.class%'
        parent: 'app.abstract_filter.form.type'
        tags:
            - { name: form.type, alias: app_string_filter}

    app.string_filter.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'app_string_filter'
            - '%app.string_filter.form.type.class%'
