parameters:
    app.project.form.type.class: AppBundle\Form\Type\ProjectType
    app.profile.form.type.class: AppBundle\Form\Type\ProfileType
    app.registration.form.type.class: AppBundle\Form\Type\RegistrationType

services:
    app.project.form.type:
        class: '%app.project.form.type.class%'
        tags:
            - { name: form.type, alias: project}

    app.project.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - 'project'
            - '%app.project.form.type.class%'

    app.profile.form:
        class: '%app.profile.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_user_profile }

    app.registration.form:
        class: '%app.registration.form.type.class%'
        tags:
            - { name: form.type, alias: myhs_user_registration }
