parameters:
    app.patient_relation_listener.class:      AppBundle\EventListener\PatientRelationListener
    app.referrer_listener.class:              AppBundle\EventListener\RefererListener

services:
    app.patient_relation_listener:
        class: '%app.patient_relation_listener.class%'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.referrer_listener:
        class: "%app.referrer_listener.class%"
        arguments: [ "@service_container" ]
        tags:
            - { name: kernel.event_subscriber }
