parameters:
    app.patient_relation_listener.class:                  AppBundle\EventListener\PatientRelationListener
    app.subdomain_listener.class:                         AppBundle\EventListener\SubdomainListener
    app.owner_listener.class:                             AppBundle\EventListener\OwnerListener
    app.acl_filter_manager.class:                         AppBundle\EventListener\AclFilterManager
    app.concession_listener.class:                        AppBundle\EventListener\ConcessionListener
    app.treatment_note_field_listener.class:              AppBundle\EventListener\TreatmentNoteFieldListener
    app.event_resource_listener.class:                    AppBundle\EventListener\EventResourceListener
    app.appointment_listener.class:                       AppBundle\EventListener\AppointmentListener
    app.appointment_notification_listener.class:          AppBundle\EventListener\AppointmentNotificationListener
    app.appointment_new_patient_listener.class:           AppBundle\EventListener\AppointmentNewPatientListener
    app.appointment_last_event_class_listener.class:      AppBundle\EventListener\AppointmentLastEventClassListener

services:
    app.patient_relation_listener:
        class: '%app.patient_relation_listener.class%'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.subdomain_listener:
        class: "%app.subdomain_listener.class%"
        arguments:
            - "@service_container"
            - "%base_host%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.acl_filter_manager:
        class: "%app.acl_filter_manager.class%"
        arguments:
            - "@security.authorization_checker"
            - "@security.token_storage"
            - '@doctrine.orm.entity_manager'
            - '@app.acl_utils'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.owner_listener:
        class: "%app.owner_listener.class%"
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    app.concession_listener:
        class: "%app.concession_listener.class%"
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.treatment_note_field_listener:
        class: "%app.treatment_note_field_listener.class%"
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.event_resource_listener:
        class: "%app.event_resource_listener.class%"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.appointment_listener:
        class: "%app.appointment_listener.class%"
        arguments:
            - "@event_dispatcher"
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.appointment_notification_listener:
        class: "%app.appointment_notification_listener.class%"
        arguments:
            - "@app.mailer"
            - "@translator.default"
            - "@app.formatter"
            - "@twig"
        tags:
            - { name: kernel.event_listener, event: appointment.created, method: onAppointmentCreated }

    app.appointment_new_patient_listener:
        class: "%app.appointment_new_patient_listener.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: appointment.created, method: onAppointmentCreated }

    app.appointment_last_event_class_listener:
        class: "%app.appointment_last_event_class_listener.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_listener, event: appointment.updated, method: onAppointmentUpdated }
            - { name: kernel.event_listener, event: appointment.created, method: onAppointmentCreated }

