parameters:
    app.main_menu_builder.class:              AppBundle\Menu\MainMenuBuilder
    app.patient_menu_builder.class:           AppBundle\Menu\PatientMenuBuilder
    app.report_menu_builder.class:            AppBundle\Menu\ReportMenuBuilder
    app.report_mobile_menu_builder.class:     AppBundle\Menu\ReportMobileMenuBuilder
    app.patient_mobile_menu_builder.class:    AppBundle\Menu\PatientMobileMenuBuilder
    app.invoice_menu_builder.class:           AppBundle\Menu\InvoiceMenuBuilder
    app.invoice_mobile_menu_builder.class:    AppBundle\Menu\InvoiceMobileMenuBuilder

services:

    app.main_menu_builder:
        class: "%app.main_menu_builder.class%"
        arguments:
            - "@knp_menu.factory"
            - "@request_stack"
            - "@security.authorization_checker"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: main }

    app.patient_menu_builder:
        class: "%app.patient_menu_builder.class%"
        arguments:
            - "@knp_menu.factory"
            - "@request_stack"
            - "@app.hasher"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: patient }

    app.patient_mobile_menu_builder:
        class: "%app.patient_mobile_menu_builder.class%"
        arguments:
            - "@knp_menu.factory"
            - "@request_stack"
            - "@app.hasher"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: patient_mobile }

    app.report_menu_builder:
        class: "%app.report_menu_builder.class%"
        arguments:
            - "@knp_menu.factory"
            - "@request_stack"
            - "@app.hasher"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: report }

    app.report_mobile_menu_builder:
        class: "%app.report_mobile_menu_builder.class%"
        arguments:
            - "@knp_menu.factory"
            - "@request_stack"
            - "@app.hasher"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: report_mobile }

    app.invoice_menu_builder:
        class: "%app.invoice_menu_builder.class%"
        arguments:
            - '@doctrine.orm.entity_manager'
            - "@knp_menu.factory"
            - "@request_stack"
            - "@router.default"
            - "@translator.default"
            - "@app.hasher"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: invoice }

    app.invoice_mobile_menu_builder:
        class: "%app.invoice_mobile_menu_builder.class%"
        parent: "app.invoice_menu_builder"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: invoice_mobile }
