parameters:
    app.request_handler.class:                                AppBundle\Handler\RequestHandler
    app.entity_action_handler.class:                          AppBundle\Handler\EntityActionHandler
    app.form_handler.class:                                   AppBundle\Handler\FormHandler
    app.entity_factory.class:                                 AppBundle\Utils\EntityFactory
    app.acl_voter.class:                                      AppBundle\Security\AclVoter
    app.acl_utils.class:                                      AppBundle\Utils\AclUtils
    app.formatter.class:                                      AppBundle\Utils\Formatter
    app.mailer.class:                                         AppBundle\Utils\AppMailer
    app.datagrid_utils.class:                                 AppBundle\Utils\DatagridUtils
    app.hasher.class:                                         AppBundle\Utils\Hasher
    app.hash_paramconverter.class:                            AppBundle\Request\ParamConverter\HashParamConverter
    app.event_utils.class:                                    AppBundle\Utils\EventUtils
    app.task_utils.class:                                     AppBundle\Utils\TaskUtils
    app.datetime_utils.class:                                 AppBundle\Utils\DateTimeUtils
    app.notificator.class:                                    AppBundle\Utils\AppNotificator
    twilio.class:                                             Twilio\Rest\Client
    app.twilio_utils.class:                                   AppBundle\Utils\TwilioUtils
    app.phone_utils.class:                                    AppBundle\Utils\PhoneUtils
    app.templater.class:                                      AppBundle\Utils\Templater
    app.treatment_note_utils.class:                           AppBundle\Utils\TreatmentNoteUtils
    app.recall_utils.class:                                   AppBundle\Utils\RecallUtils

    app.validator.event_not_overlap.class:                    AppBundle\Validator\EventNotOverlapValidator
    app.validator.сalendar_data_end_more_than_start.class:    AppBundle\Validator\CalendarSettingsEndMoreThanStartValidator
    app.validator.calendar_settings_dates_not_equal.class:    AppBundle\Validator\CalendarSettingsDatesNotEqualValidator
    app.validator.invoice_counter.class:                      AppBundle\Validator\InvoiceCounterValidator
    app.validator.patient_phone_main.class:                   AppBundle\Validator\PatientPhoneNumberValidator
    app.validator.patient_phone.class:                        AppBundle\Validator\PhoneNumberValidator

    app.products_fixture.class:                               AppBundle\DataFixtures\ORM\LoadProductsData

services:
    app.request_handler:
        class: '%app.request_handler.class%'

    app.form_handler:
        class: '%app.form_handler.class%'
        arguments:
            - '@validator'

    app.entity_action_handler:
        class: '%app.entity_action_handler.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.form_handler'
            - '@app.request_handler'
            - '@request_stack'
            - '@router'
            - '@session'
            - '@app.hasher'
            - '@twig'

    app.entity_factory:
        class: '%app.entity_factory.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'

    app.formatter:
        arguments:
            - '@app.phone_utils'
        class: '%app.formatter.class%'

    app.templater:
        class: '%app.templater.class%'
        arguments:
            - '@twig'

    app.notificator:
        class: '%app.notificator.class%'
        arguments:
            - '@app.mailer'
            - '@twilio'
            - '@app.twilio_utils'
            - '@twig'
            - '@app.formatter'
            - '@doctrine.orm.entity_manager'

    app.mailer:
        class: '%app.mailer.class%'
        arguments:
            - '@mailer'
            - '@swiftmailer.transport.real'
            - '%mailer_from_address%'
            - '%mailer_from_name%'

    app.acl_voter:
        class: '%app.acl_voter.class%'
        arguments:
            - '@app.acl_utils'
        tags:
            - { name: security.voter }
        public: false

    app.acl_utils:
        class: '%app.acl_utils.class%'

    app.datagrid_utils:
        class: '%app.datagrid_utils.class%'
        arguments:
            - '@app.form_handler'
            - '@knp_paginator'
            - '@twig'

    app.datetime_utils:
        class: '%app.datetime_utils.class%'

    app.hasher:
        class: '%app.hasher.class%'
        arguments:
            - '%hash_id_salt%'
            - '%hash_id_padding%'
            - '@session'

    app.hash_paramconverter:
        class: "%app.hash_paramconverter.class%"
        arguments:
            - "@doctrine"
            - "@app.hasher"
        tags:
            - { name: request.param_converter, priority: 2, converter: hash }

    app.event_utils:
        class: "%app.event_utils.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.hasher"
            - "@translator.default"
            - "@request_stack"
            - "@app.formatter"
            - "@security.token_storage"

    app.recall_utils:
        class: "%app.recall_utils.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.hasher"
            - "@translator.default"
            - "@request_stack"
            - "@app.formatter"
            - "@security.token_storage"

    app.treatment_note_utils:
        class: "%app.treatment_note_utils.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@translator.default"

    app.task_utils:
        class: "%app.task_utils.class%"
        arguments:
            - "@doctrine.orm.entity_manager"

    app.validator.event_not_overlap:
        class: "%app.validator.event_not_overlap.class%"
        arguments:
            - "@app.event_utils"
        tags:
            - { name: validator.constraint_validator, alias: eventNotOverlap }

    app.validator.сalendar_data_end_more_than_start:
        class: "%app.validator.сalendar_data_end_more_than_start.class%"
        arguments:
            - "@app.formatter"
        tags:
            - { name: validator.constraint_validator, alias: сalendarDataEndMoreThanStart }

    app.validator.calendar_settings_dates_not_equal:
        class: "%app.validator.calendar_settings_dates_not_equal.class%"
        arguments:
            - "@app.formatter"
        tags:
            - { name: validator.constraint_validator, alias: calendarSettingsDatesNotEqual }

    app.validator.invoice_counter:
        class: "%app.validator.invoice_counter.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: invoiceCounter }

    app.validator.patient_phone:
        class: "%app.validator.patient_phone.class%"
        arguments:
            - "@app.phone_utils"
        tags:
            - { name: validator.constraint_validator, alias: patientPhone }

    app.validator.patient_phone_main:
        class: "%app.validator.patient_phone_main.class%"
        arguments:
            - "@app.phone_utils"
        tags:
            - { name: validator.constraint_validator, alias: patientPhoneMain }

    twilio:
        class: '%twilio.class%'
        arguments:
            - '%twilio_sid%'
            - '%twilio_token%'

    app.twilio_utils:
        class: "%app.twilio_utils.class%"
        arguments:
            - "@twilio"
            - "@doctrine.orm.entity_manager"

    app.phone_utils:
        class: "%app.phone_utils.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
