parameters:
    app.request_handler.class:                AppBundle\Handler\RequestHandler
    app.entity_action_handler.class:          AppBundle\Handler\EntityActionHandler
    app.form_handler.class:                   AppBundle\Handler\FormHandler
    app.entity_factory.class:                 AppBundle\Utils\EntityFactory
    app.patient_relation_listener.class:      AppBundle\EventListener\PatientRelationListener
    app.price_extension.class:                AppBundle\Twig\PriceExtension
    app.profile_menu_builder.class:           AppBundle\Menu\ProfileMenuBuilder
    app.patient_menu_builder.class:           AppBundle\Menu\PatientMenuBuilder

services:
    app.request_handler:
        class: '%app.request_handler.class%'

    app.form_handler:
        class: '%app.form_handler.class%'
        arguments:
            - '@validator'

    app.entity_action_handler:
        class: '%app.entity_action_handler.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.form_handler'
            - '@app.request_handler'
            - '@request_stack'
            - '@router'

    app.entity_factory:
        class: '%app.entity_factory.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'

    app.patient_relation_listener:
        class: '%app.patient_relation_listener.class%'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    app.price_extension:
        class: "%app.price_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    app.profile_menu_builder:
        class: "%app.profile_menu_builder.class%"
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: profile }

    app.patient_menu_builder:
        class: "%app.patient_menu_builder.class%"
        arguments:
            - "@knp_menu.factory"
            - "@request_stack"
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: patient }

