parameters:
    app.request_handler.class:                AppBundle\Handler\RequestHandler
    app.entity_action_handler.class:          AppBundle\Handler\EntityActionHandler
    app.form_handler.class:                   AppBundle\Handler\FormHandler
    app.entity_factory.class:                 AppBundle\Utils\EntityFactory
    app.acl_voter.class:                      AppBundle\Security\AclVoter
    app.acl_utils.class:                      AppBundle\Utils\AclUtils
    app.formatter.class:                      AppBundle\Utils\Formatter
    app.mailer.class:                         AppBundle\Utils\AppMailer
    app.datagrid_utils.class:                 AppBundle\Utils\DatagridUtils
    app.hasher.class:                         AppBundle\Utils\Hasher
    app.hash_paramconverter.class:            AppBundle\Request\ParamConverter\HashParamConverter
    app.event_utils.class:                    AppBundle\Utils\EventUtils

services:
    app.request_handler:
        class: '%app.request_handler.class%'

    app.form_handler:
        class: '%app.form_handler.class%'
        arguments:
            - '@validator'

    app.entity_action_handler:
        class: '%app.entity_action_handler.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.form_handler'
            - '@app.request_handler'
            - '@request_stack'
            - '@router'
            - '@session'
            - '@app.hasher'
            - '@twig'

    app.entity_factory:
        class: '%app.entity_factory.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'

    app.formatter:
        class: '%app.formatter.class%'

    app.mailer:
        class: '%app.mailer.class%'
        arguments:
            - '@mailer'
            - '@swiftmailer.transport.real'
            - '%mailer_from_address%'
            - '%mailer_from_name%'

    app.acl_voter:
        class: '%app.acl_voter.class%'
        arguments:
            - '@app.acl_utils'
        tags:
            - { name: security.voter }
        public: false

    app.acl_utils:
        class: '%app.acl_utils.class%'

    app.datagrid_utils:
        class: '%app.datagrid_utils.class%'
        arguments:
            - '@app.form_handler'
            - '@knp_paginator'
            - '@twig'

    app.hasher:
        class: '%app.hasher.class%'
        arguments:
            - '%hash_id_salt%'
            - '%hash_id_padding%'
            - '@session'

    app.hash_paramconverter:
        class: "%app.hash_paramconverter.class%"
        arguments:
            - "@doctrine"
            - "@app.hasher"
        tags:
            - { name: request.param_converter, priority: 2, converter: hash }

    app.event_utils:
        class: "%app.event_utils.class%"
