parameters:
    app.price_extension.class:                AppBundle\Twig\PriceExtension
    app.byte_conversion_twig_extension.class: AppBundle\Twig\ByteConversionTwigExtension
    app.formatter_extension.class:            AppBundle\Twig\FormatterExtension
    app.hasher_extension.class:               AppBundle\Twig\HasherExtension
    app.referrer_extension.class:             AppBundle\Twig\ReferrerExtension

services:
    app.price_extension:
        class: "%app.price_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    app.formatter_extension:
        class: "%app.formatter_extension.class%"
        arguments:
            - '@app.formatter'
        public: false
        tags:
            - { name: twig.extension }

    app.byte_conversion.twig.extension:
        class: "%app.byte_conversion_twig_extension.class%"
        tags:
            - { name: twig.extension }

    app.hasher.twig.extension:
        class: "%app.hasher_extension.class%"
        tags:
            - { name: twig.extension }
        calls:
            - ["setHasher",["@app.hasher"]]

    app.referrer.twig.extension:
        class: "%app.referrer_extension.class%"
        tags:
            - { name: twig.extension }
        calls:
            - ["setDependencies",["@doctrine.orm.entity_manager",'@router',"@app.hasher"]]
