parameters:
    app.price_extension.class:                AppBundle\Twig\PriceExtension
    app.byte_conversion_twig_extension.class: AppBundle\Twig\ByteConversionTwigExtension

services:
    app.price_extension:
        class: "%app.price_extension.class%"
        public: false
        tags:
            - { name: twig.extension }

    app.byte_conversion.twig.extension:
        class: %app.byte_conversion_twig_extension.class%
        tags:
            - { name: twig.extension }
