AppBundle\Entity\DocumentCategory:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\Document:
    properties:
        file:
            - File:
                maxSize: 20000000
                mimeTypes:
                    - image/png
                    - image/jpeg
                    - image/jpg
                    - image/gif
                    - application/msword
                    - application/vnd.ms-office
                    - application/pdf
                    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                    - text/plain

AppBundle\Entity\Country:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\Goal:
    properties:
        goal:
            - NotBlank: ~
        when:
            - NotBlank: ~

AppBundle\Entity\State:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        country:
            - NotBlank: ~

AppBundle\Entity\Subscription:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        duration:
            - NotBlank: ~
        price:
            - NotBlank: ~

AppBundle\Entity\Refund:
    properties:
        items:
            - Valid: ~

AppBundle\Entity\CommunicationEvent:
    properties:
        description:
            - NotBlank: ~
        patient:
            - NotBlank: ~
        date:
            - NotBlank: ~
        color:
            - NotBlank: ~

AppBundle\Entity\InvoiceRefund:
    properties:
        amount:
            - NotBlank: ~
        refund:
            - NotBlank: ~
        paymentMethod:
            - NotBlank: ~

AppBundle\Entity\PatientAlert:
    properties:
        text:
            - NotBlank: ~

AppBundle\Entity\RecurringTask:
    properties:
        startDate:
            - NotBlank: ~
        text:
            - NotBlank: ~

AppBundle\Entity\Recall:
    constraints:
        - AppBundle\Validator\RecallCorrect: { groups: [Submit] }
    properties:
        patient:
            - NotBlank: { groups: [Default] }
        date:
            - NotBlank: { groups: [Default] }

AppBundle\Entity\ManualCommunication:
    constraints:
        - AppBundle\Validator\ManualCommunicationCorrect: { groups: [Default, Submit] }
    properties:
        communicationType:
            - NotBlank: { groups: [Default,Submit] }
    getters:
        addresseeCorrect:
            - "IsTrue": { message: 'app.patient.choose', groups: [Default,Submit] }

AppBundle\Entity\Patient:
    constraints:
        - AppBundle\Validator\PatientPhoneNumber:
            groups: [Default, Appointment]
    properties:
        firstName:
            - NotBlank:  { groups: [Default, Appointment] }
            - Length:
                min: 2
                max: 30
                groups: [Default, Appointment]
        lastName:
            - NotBlank: { groups: [Default, Appointment] }
            - Length:
                min: 2
                max: 30
                groups: [Default, Appointment]
        gender:
            - NotBlank: ~
        referrer:
            - NotBlank: { groups: [Default, Appointment] }
        mobilePhone:
            - NotBlank: { groups: [Default, Appointment] }
            #- Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
            #    defaultRegion: AU
            #    groups: [Default, Appointment]
            - Regex:
                pattern: '/^[0-9\s\+\-\(\)]+$/'
                groups: [Default, Appointment]
        email:
            - Email: { groups: [Default, Appointment] }
        postCode:
            - Regex: '/^\d+/'
        phones:
            - Valid: ~
        relatedPatients:
            - Valid: ~

AppBundle\Entity\Phone:
    constraints:
        - AppBundle\Validator\PhoneNumber: ~
    properties:
        phoneNumber:
            - NotBlank: ~
            #- Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
            #    defaultRegion: AU
            - Regex:
                pattern: '/^[0-9\s\+\-\(\)]+$/'
        phoneType:
            - NotBlank: ~
            - Length:
                min: 2
                max: 30
    #getter:
    #    ok: ~

AppBundle\Entity\RelatedPatient:
    properties:
        patientRelationship:
            - NotBlank: ~
        mainPatient:
            - NotBlank: ~
        patient:
            - NotBlank: ~

AppBundle\Entity\TreatmentNoteTemplate:
    properties:
        name:
            - NotBlank: ~
        treatmentNoteFields:
            - Valid: ~
            #- Count:
            #    min: 1

AppBundle\Entity\TreatmentPackCredit:
    properties:
        invoiceProduct:
            - NotBlank: ~
        patient:
            - NotBlank: ~

AppBundle\Entity\TreatmentNoteField:
    properties:
        name:
            - NotBlank: ~
        position:
            - NotBlank: ~

AppBundle\Entity\Product:
    properties:
        #name:
        #    - NotBlank: ~
        #price:
        #    - NotBlank: ~
        #    - Range:
        #        max: 99999999
        concessionPrices:
            - Valid: ~
        stockLevel:
            - NotBlank: ~
            - Range:
                max: 99999999
            #- Regex:
            #    pattern: '/^[0-9]*$/'

AppBundle\Entity\Treatment:
    properties:
        name:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        concessionPrices:
            - Valid: ~
        attachment:
            - File:
                maxSize: 20000000
                mimeTypes:
                    - application/msword
                    - application/pdf
                    - application/vnd.openxmlformats-officedocument.wordprocessingml.document

AppBundle\Entity\Concession:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\ConcessionPrice:
    properties:
        concessionPriceOwner:
            - NotBlank: ~
        concession:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Range:
                max: 99999999

AppBundle\Entity\EventRecurrency:
    properties:
        type:
            - NotBlank: ~

AppBundle\Entity\RecallFor:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\Invoice:
    properties:
        name:
            - NotBlank: ~
        date:
            - NotBlank: ~
        #patient:
        #    - NotBlank: ~
        dueDate:
            - NotBlank: ~
            - Range:
                min: 0
            - Length:
                min: 1
                max: 3
        invoiceProducts:
            - Valid: ~
        invoiceTreatments:
            - Valid: ~
        payments:
            - Valid: ~

AppBundle\Entity\InvoicePayment:
    properties:
        date:
            - NotBlank: ~
        amount:
            - NotBlank: ~
            - GreaterThan:
                value: 0
        paymentMethod:
            - NotBlank: ~
    getters:
        amountCorrect:
            - "IsTrue": { message: 'app.invoice_payment.too_big_amount' }

AppBundle\Entity\InvoicePaymentMethod:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\Event:
    constraints:
        - AppBundle\Validator\EventNotOverlap: ~
    getters:
        datesNotEqual:
            - "IsTrue": { message: 'app.event.equal_dates' }
        endMoreThanStart:
            - "IsTrue": { message: 'app.event.end_more_than_start' }
    properties:
        resource:
            - NotBlank: ~

AppBundle\Entity\EventResource:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\Appointment:
    properties:
        patient:
            - NotBlank: ~
            - Valid: ~
        treatment:
            - NotBlank: ~

AppBundle\Entity\CalendarSettings:
    constraints:
        - AppBundle\Validator\CalendarSettingsEndMoreThanStart: ~
        - AppBundle\Validator\CalendarSettingsDatesNotEqual: ~
    properties:
        workDayStart:
            - NotBlank: ~
        workDayEnd:
            - NotBlank: ~
        timeInterval:
            - NotBlank: ~
            - Range:
                min: 1
                max: 60
        resources:
            - Valid: ~

AppBundle\Entity\CommunicationsSettings:
    properties:
        fromEmailAddress:
            - NotBlank: ~
            - Email: ~
        appointmentCreationEmail:
            - NotBlank: ~
        appointmentCreationSms:
            - NotBlank: ~
        appointmentReminderEmail:
            - NotBlank: ~
        appointmentReminderSms:
            - NotBlank: ~
        recallEmail:
            - NotBlank: ~
        recallSms:
            - NotBlank: ~
        whenRemainderEmailSentDay:
            - NotBlank: ~
            - Range:
                min: 0
        whenRemainderEmailSentTime:
            - NotBlank: ~
        whenRemainderSmsSentDay:
            - NotBlank: ~
            - Range:
                min: 0
        whenRemainderSmsSentTime:
            - NotBlank: ~

AppBundle\Entity\InvoiceSettings:
    constraints:
        - AppBundle\Validator\InvoiceCounter: ~
    properties:
        dueWithin:
            - NotBlank: ~
        invoiceTitle:
            - NotBlank: ~
        invoiceNumber:
            - NotBlank: ~
            - Range:
                min: 1

AppBundle\Entity\InvoiceProduct:
    properties:
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        product:
            - NotBlank: ~
        invoice:
            - NotBlank: ~
        quantity:
            - NotBlank: ~
            - Range:
                min: 1

AppBundle\Entity\InvoiceTreatment:
    properties:
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        treatment:
            - NotBlank: ~
        invoice:
            - NotBlank: ~
        quantity:
            - NotBlank: ~
            - Range:
                min: 1

AppBundle\Entity\Attachment:
    properties:
        file:
            - File:
                maxSize: 20000000
                mimeTypes:
                    - image/png
                    - image/jpeg
                    - image/jpg
                    - image/gif
                    - application/msword
                    - application/vnd.ms-office
                    - application/pdf
                    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                    - text/plain

AppBundle\Entity\InvoiceLogo:
    properties:
        file:
            - File:
                maxSize: 20000000
                mimeTypes:
                    - image/png
                    - image/jpeg
                    - image/jpg
                    - image/gif
