AppBundle\Entity\Country:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\State:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        country:
            - NotBlank: ~

AppBundle\Entity\Subscription:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        duration:
            - NotBlank: ~
        price:
            - NotBlank: ~

AppBundle\Entity\PatientAlert:
    properties:
        text:
            - NotBlank: ~

AppBundle\Entity\Patient:
    properties:
        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 30
        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 30
        gender:
            - NotBlank: ~
        referrer:
            - NotBlank: ~
        mobilePhone:
            - NotBlank: ~
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                defaultRegion: AU
            - Regex:
                pattern: '/^[0-9\s\+\-\(\)]+$/'
        email:
            - Email: ~
        phones:
            - Valid: ~
        relatedPatients:
            - Valid: ~

AppBundle\Entity\Phone:
    properties:
        phoneNumber:
            - NotBlank: ~
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber:
                defaultRegion: AU
            - Regex:
                pattern: '/^[0-9\s\+\-\(\)]+$/'
        phoneType:
            - NotBlank: ~
            - Length:
                min: 2
                max: 30
    getter:
        ok: ~

AppBundle\Entity\RelatedPatient:
    properties:
        patientRelationship:
            - NotBlank: ~
        mainPatient:
            - NotBlank: ~
        patient:
            - NotBlank: ~

AppBundle\Entity\TreatmentNoteTemplate:
    properties:
        name:
            - NotBlank: ~
        treatmentNoteFields:
            - Valid: ~
            #- Count:
            #    min: 1

AppBundle\Entity\TreatmentNoteField:
    properties:
        name:
            - NotBlank: ~
        position:
            - NotBlank: ~

AppBundle\Entity\Product:
    properties:
        name:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        concessionPrices:
            - Valid: ~
        stockLevel:
            - Range:
                max: 99999999
            #- Regex:
            #    pattern: '/^[0-9]*$/'

AppBundle\Entity\Treatment:
    properties:
        name:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        concessionPrices:
            - Valid: ~

AppBundle\Entity\Concession:
    properties:
        name:
            - NotBlank: ~

AppBundle\Entity\ConcessionPrice:
    properties:
        concessionPriceOwner:
            - NotBlank: ~
        concession:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Range:
                max: 99999999

AppBundle\Entity\Invoice:
    properties:
        name:
            - NotBlank: ~
        date:
            - NotBlank: ~
        patient:
            - NotBlank: ~
        dueDate:
            - NotBlank: ~
            - Range:
                min: 1
            - Length:
                min: 1
                max: 3
        invoiceProducts:
            - Valid: ~
        invoiceTreatments:
            - Valid: ~

AppBundle\Entity\Appointment:
    properties:
        patient:
            - NotBlank: ~
        treatment:
            - NotBlank: ~

AppBundle\Entity\InvoiceProduct:
    properties:
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        product:
            - NotBlank: ~
        invoice:
            - NotBlank: ~
        quantity:
            - NotBlank: ~
            - Range:
                min: 1

AppBundle\Entity\InvoiceTreatment:
    properties:
        price:
            - NotBlank: ~
            - Range:
                max: 99999999
        treatment:
            - NotBlank: ~
        invoice:
            - NotBlank: ~
        quantity:
            - NotBlank: ~
            - Range:
                min: 1

AppBundle\Entity\Attachment:
    properties:
        file:
            - File:
                maxSize: 20000000
                mimeTypes:
                    - image/png
                    - image/jpeg
                    - image/jpg
                    - image/gif
                    - application/msword
                    - application/pdf
                    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
                    - text/plain
